version: '3.3'
services:
  db:
    image: guraiah93/db:${TAG}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_ROOT_USER: root
 
  app: 
    image: guraiah93/app:${TAG}
    ports: 
       - '8085:80'

